default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000
  username: <%= ENV['PSQL_name'] %>
  password: <%= ENV['PSQL_psw'] %>


development:
  <<: *default
  database: devguru

test:
  <<: *default
  database: testguru

production:
  <<: *default
  database: prodguru
